plugins {
    // 1. Android plugins MUST come first
    id 'com.android.application'

    // 2. Then apply dependent plugins like Safe Args and Hilt
    id 'androidx.navigation.safeargs'
    id 'dagger.hilt.android.plugin'
    id 'io.sentry.android.gradle' version '3.1.3'
    id("org.jetbrains.kotlin.android")

    // Add this line:
    id("org.jetbrains.kotlin.kapt")
}


android {
    dataBinding {
        enabled true
    }
    compileSdk 35

    defaultConfig {
        applicationId "com.darcangel.tcamViewer"
        minSdk 26
        targetSdk 35
        versionName "nameExt"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    defaultConfig {
        versionCode 4022302
        versionName "0.3.6"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
        applicationVariants.all {
                // this method is use to rename your all apk whether
                // it may be signed or unsigned(debug apk)
            variant ->
                variant.outputs.each{
                        // on below line we are setting a name to our apk
                    output->
                        def buildType =  variant.buildType.name
                        // on below line we are specifying our app name.
                        project.ext { appName = 'tcamViewer' }
                        // on below line we are creating a new name for our apk.
                        def newName = output.outputFile.name
                        // on below line we are replacing our previous name with our app name.
                        newName = newName.replace("app_", "$project.ext.appName-")
                        // on below line we are replacing -debug with our formatted date.
                        newName = newName.replace("-" + buildType, "_" + buildType + "_" + "v" + versionName)
                        // at last we are setting our apk name to it.
                        output.outputFileName  = newName
                }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }


    buildFeatures {
        viewBinding true
        dataBinding true
    }

    hilt {
        enableAggregatingTask = true
    }
    namespace 'com.darcangel.tcamViewer'
}

dependencies {
    // Individual Libraries
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.material)

    // RecyclerView & Selection
    implementation(libs.androidx.recyclerview)
    implementation(libs.androidx.recyclerview.selection)

    // Using Bundles (Groups multiple libraries into one line)
    implementation(libs.bundles.navigation)
    implementation(libs.bundles.lifecycle)
    implementation(libs.bundles.moshi)

    implementation(libs.reactivex.rxjava)
    implementation(libs.reactivex.rxandroid) // Only needed for Android projects
    implementation(libs.manifold.ext)        //    implementation libs.rxdogtag

    implementation(libs.timber)

    // Dependency Injection & Annotation Processors
    implementation(libs.dagger.hilt.android)
    kapt(libs.dagger.hilt.compiler) // Or annotationProcessor(libs.dagger.hilt.compiler)

    // Handling Dependencies with Exclusions
    implementation(libs.socket.io.client)

    // Testing
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.androidx.espresso.core)
}

